name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install Netlify
      run: npm install netlify-cli -g

    - name: Install dependencies
      run: yarn install

    - name: Build application
      run: yarn run build
      env:
        CI: ""

    - name: Deploy to Netlify
      run: |
        echo "/* /index.html 200" > ./build/_redirects
        netlify deploy --prod --dir "./build" --site=${{secrets.NETLIFY_SITE_ID}} --auth=${{secrets.NETLIFY_PAT}} --timeout=600 --message "Deployed on $(date)"

